# Generated by Django 4.1.3 on 2022-11-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transacao_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
