# Generated by Django 4.1.3 on 2022-11-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_remove_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
