# Generated by Django 4.1.3 on 2022-11-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
